name: Terraform Code Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install SonarScanner
        run: |
          # Download SonarScanner ZIP
          wget -q -O sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"
          # Extract SonarScanner
          unzip -q sonar-scanner.zip
          # Set up PATH
          export PATH=$PATH:$RUNNER_WORKSPACE/sonar-scanner-4.7.0.2747-linux/bin
          # Verify installation
          sonar-scanner --version

      - name: Run SonarScanner
        run: |
          sonar-scanner

      - name: Upload SonarQube Analysis
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./sonarqube/out/sonar-project-*.sarif

  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONAR_TOKEN }}
