name: SonarCloud Scan

on:
  push:
    branches:
      - master  # Adjust branch name if needed
  pull_request:
    branches:
      - master  # Adjust branch name if needed

jobs:
  sonarcloud_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: SonarCloud Scan
        run: |
          sonar-scanner \
          -Dsonar.organization=testsonnarforgithubravi \
          -Dsonar.projectKey=testsonnarforgithubravi_testsonnarforgithubravi \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Upload SonarCloud Quality Gate status
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/sonar/sonar-report.json
