name: Terraform Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tfsec-analysis:
    name: Terraform Security Analysis
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install tfsec
      - name: Install tfsec
        run: |
          curl -fsSL https://aquasecurity.github.io/tfsec/install.sh | sh

      # Run tfsec analysis and generate SARIF report
      - name: Run tfsec and generate SARIF report
        run: |
          tfsec path/to/terraform/files --format sarif --out tfsec_report.sarif

      # Upload SARIF report to GitHub
      - name: Upload SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec_report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
