name: SonarCloud Scan

on:
  push:
    branches:
      - master  # Adjust branch name if needed
  pull_request:
    branches:
      - master  # Adjust branch name if needed

jobs:
  sonarcloud_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: SonarCloud Scan
        run: |
          wget -q -O sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip"
          ls -l
          unzip -q sonar-scanner.zip
          echo "-------+++++++"
          ls -l /home/runner/work/
          echo "-------"
          ls -l /home/runner/work/PyMYSQL-class/PyMYSQL-class/
          echo "++++++++"
          ls -l /home/runner/work/PyMYSQL-class/PyMYSQL-class/sonar-scanner-5.0.1.3006-linux/
          echo "========="
          ls -l $RUNNER_WORKSPACE
          echo "++++++++++++==="
          export PATH=$PATH:$RUNNER_WORKSPACE/PyMYSQL-class/sonar-scanner-5.0.1.3006-linux/bin/
          $RUNNER_WORKSPACE/PyMYSQL-class/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner --version
          $RUNNER_WORKSPACE/PyMYSQL-class/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
            -Dsonar.projectKey=raviSanchala_PyMYSQL-class \
            -Dsonar.organization=ravisanchala123456
            -Dsonar.sources=. \
            -Dsonar.inclusions=**/*.tf \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.language=terraform

      - name: Upload SonarCloud Quality Gate status
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/sonar/sonar-report.json
