name: Terraform Code Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code_scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install SonarScanner
        run: |
          ls -l 
          echo  "__"
          ls -l $RUNNER_WORKSPACE
          echo "++"
          wget -q -O sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.1.3023-linux.zip"
          unzip -q sonar-scanner.zip
          ls -l
          echo "-----"
          ls -l sonar-scanner-4.8.1.3023-linux
          echo "==="
          ls -l sonar-scanner-4.8.1.3023-linux/bin/sonar-scanner
          chmod +x sonar-scanner-4.8.1.3023-linux/bin/sonar-scanner
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          export PATH=$PATH:$RUNNER_WORKSPACE/PyMYSQL-class/sonar-scanner-4.8.1.3023-linux/bin
          echo "Hi:"
          ls -l $RUNNER_WORKSPACE/PyMYSQL-class
          sonar-scanner --version
          mkdir -p $(dirname ./coverage-report.xml)
          sonar-scanner \
            -Dsonar.projectKey=raviSanchala_PyMYSQL-class1 \
            -Dsonar.organization=ravisanchala97980798797797098078
            -Dsonar.host.url=https://sonarcloud.io \
            #-Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.login=70a739b14d79033cf77fc72c3a1502c62e4a7795
            -Dsonar.sources=. \
            -Dsonar.inclusions=**/*.tf \
            -Dsonar.language=terraform \
            -Dsonar.verbose=true
                 
