name: Terraform Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trivy-analysis:
    name: Terraform Security Analysis
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://aquasecurity.github.io/trivy-repo/get | sh
          which trivy
          

      # Run Trivy analysis on Terraform files and generate SARIF report
      - name: Run Trivy and generate SARIF report
        run: |
          trivy fs --security-checks vuln ./ --format sarif --output trivy_report.sarif

      # Upload SARIF Report to GitHub
      - name: Upload SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy_report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
