name: Terraform Security Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tfsec-analysis:
    name: Terraform Security Analysis
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the latest version of tfsec from GitHub using go install
      - name: Install tfsec
        run: |
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

          # Verify installation
          which tfsec

      # Run tfsec analysis on Terraform files and generate SARIF report
      - name: Run tfsec and generate SARIF report
        run: |
          tfsec . --format sarif --out tfsec_report.sarif
        # Specify the directory containing your Terraform files

      # Upload SARIF Report to GitHub
      - name: Upload SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec_report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
